### ISSUE TITLE
Rendering bilaterally

### ISSUE THREAD

**Issue by Zumbalamambo** [dragonkhoi/suvstar#1]
Thanks for the amazing code. I tried `HelloAR_SUVSTAR.unity`. Unfortunately, it has view only for the left eye. Could you please tell me how I can render the view on both eyes?

**Comment by dragonkhoi** [comment]
Hello @Zumbalamambo, if you are trying to make this work on two phones; go to Cameras->PostRenderCamera to the component: SUVSTARPostRender and check the bool "IsLeft." Build to the first phone that will go in front of your left eye. Then uncheck the bool "IsLeft" and build to the second phone that will go in front of your right eye. If you are trying to have a single phone with passthrough, make sure the RenderTexture is the exact resolution and aspect ratio of your device; go into SUVSTARPostRender.cs and change e < 1 to e < 2; this will render both eyes instead of just one. Finally, disable the Canvas with all the UI buttons so they don't get in the way. We just updated the README and commented a lot of the code!

**Comment by Zumbalamambo** [comment]
Thanks for the suggestions and the thorough comments @dragonkhoi I'm trying to render it in a single device (Mi8). I changed it to `e<2`. I have also changed m_Width and  m_Height as `m_Width: 2248 m_Height: 1080` in   StereoScreen.rendertexture. but for some reason, I'm able to see only one eye. Do you have any suggestion? An example picture of the view that I'm trying to achieve is as follows, 

![Picture1-3](https://user-images.githubusercontent.com/24539006/59330965-1c39c380-8cf3-11e9-8cd0-00cabb0c3691.png)

It won't be circular as in the picture but the barrel distorted has to be on both right, left eye.
